COMP003B.AssignmentFinal/Models/Specialty.cs
using System.ComponentModel.DataAnnotations;

namespace COMP003B.AssignmentFinal.Models
{
	public class Specialty
	{
		public int SpecialtyId { get; set; }

     
        [Required]
		public string SpecialtyName { get; set; }
		[Required]
		public string SpecialtyType { get; set; }

		// Collection navigation property
		public virtual ICollection<TrainerSpecialty>? TrainerSpecialties { get; set; }
	}
}

COMP003B.AssignmentFinal/Controllers/SpecialtiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using COMP003B.AssignmentFinal.Data;
using COMP003B.AssignmentFinal.Models;

namespace COMP003B.AssignmentFinal.Controllers
{
    public class SpecialtiesController : Controller
    {
        private readonly WebDevAcademyContext _context;

        public SpecialtiesController(WebDevAcademyContext context)
        {
            _context = context;
        }

        // GET: Specialties
        public async Task<IActionResult> Index()
        {
              return _context.Specialties != null ? 
                          View(await _context.Specialties.ToListAsync()) :
                          Problem("Entity set 'WebDevAcademyContext.Specialties'  is null.");
        }

        // GET: Specialties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Specialties == null)
            {
                return NotFound();
            }

            var specialty = await _context.Specialties
                .FirstOrDefaultAsync(m => m.SpecialtyId == id);
            if (specialty == null)
            {
                return NotFound();
            }

            ViewBag.Trainers = from s in _context.Trainers
                               join e in _context.TrainerSpecialties on s.TrainerId equals e.TrainerId
                               join c in _context.Specialties on e.SpecialtyId equals c.SpecialtyId
                               where c.SpecialtyId == id
                               select s;

            return View(specialty);
        }

        // GET: Specialties/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Specialties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SpecialtyId,SpecialtyName,SpecialtyType")] Specialty specialty)
        {
            if (ModelState.IsValid)
            {
                _context.Add(specialty);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(specialty);
        }

        // GET: Specialties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Specialties == null)
            {
                return NotFound();
            }

            var specialty = await _context.Specialties.FindAsync(id);
            if (specialty == null)
            {
                return NotFound();
            }
            return View(specialty);
        }

        // POST: Specialties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SpecialtyId,SpecialtyName,SpecialtyType")] Specialty specialty)
        {
            if (id != specialty.SpecialtyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(specialty);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpecialtyExists(specialty.SpecialtyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(specialty);
        }

        // GET: Specialties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Specialties == null)
            {
                return NotFound();
            }

            var specialty = await _context.Specialties
                .FirstOrDefaultAsync(m => m.SpecialtyId == id);
            if (specialty == null)
            {
                return NotFound();
            }

            return View(specialty);
        }

        // POST: Specialties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Specialties == null)
            {
                return Problem("Entity set 'WebDevAcademyContext.Specialties'  is null.");
            }
            var specialty = await _context.Specialties.FindAsync(id);
            if (specialty != null)
            {
                _context.Specialties.Remove(specialty);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SpecialtyExists(int id)
        {
          return (_context.Specialties?.Any(e => e.SpecialtyId == id)).GetValueOrDefault();
        }
    }
}

COMP003B.AssignmentFinal/Controllers/TrainerSpecialtiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using COMP003B.AssignmentFinal.Data;
using COMP003B.AssignmentFinal.Models;

namespace COMP003B.AssignmentFinal.Controllers
{
    public class TrainerSpecialtiesController : Controller
    {
        private readonly WebDevAcademyContext _context;

        public TrainerSpecialtiesController(WebDevAcademyContext context)
        {
            _context = context;
        }

        // GET: TrainerSpecialties
        public async Task<IActionResult> Index()
        {
            var webDevAcademyContext = _context.TrainerSpecialties.Include(t => t.Specialty).Include(t => t.Trainer);
            return View(await webDevAcademyContext.ToListAsync());
        }

        // GET: TrainerSpecialties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TrainerSpecialties == null)
            {
                return NotFound();
            }

            var trainerSpecialty = await _context.TrainerSpecialties
                .Include(t => t.Specialty)
                .Include(t => t.Trainer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (trainerSpecialty == null)
            {
                return NotFound();
            }

            return View(trainerSpecialty);
        }

        // GET: TrainerSpecialties/Create
        public IActionResult Create()
        {
            ViewData["SpecialtyId"] = new SelectList(_context.Specialties, "SpecialtyId", "SpecialtyName");
            ViewData["TrainerId"] = new SelectList(_context.Trainers, "TrainerId", "TrainerName");
            return View();
        }

        // POST: TrainerSpecialties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TrainerId,SpecialtyId")] TrainerSpecialty trainerSpecialty)
        {
            if (ModelState.IsValid)
            {
                _context.Add(trainerSpecialty);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SpecialtyId"] = new SelectList(_context.Specialties, "SpecialtyId", "SpecialtyName", trainerSpecialty.SpecialtyId);
            ViewData["TrainerId"] = new SelectList(_context.Trainers, "TrainerId", "TrainerName", trainerSpecialty.TrainerId);
            return View(trainerSpecialty);
        }

        // GET: TrainerSpecialties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TrainerSpecialties == null)
            {
                return NotFound();
            }

            var trainerSpecialty = await _context.TrainerSpecialties.FindAsync(id);
            if (trainerSpecialty == null)
            {
                return NotFound();
            }
            ViewData["SpecialtyId"] = new SelectList(_context.Specialties, "SpecialtyId", "SpecialtyName", trainerSpecialty.SpecialtyId);
            ViewData["TrainerId"] = new SelectList(_context.Trainers, "TrainerId", "TrainerName", trainerSpecialty.TrainerId);
            return View(trainerSpecialty);
        }

        // POST: TrainerSpecialties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TrainerId,SpecialtyId")] TrainerSpecialty trainerSpecialty)
        {
            if (id != trainerSpecialty.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trainerSpecialty);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrainerSpecialtyExists(trainerSpecialty.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SpecialtyId"] = new SelectList(_context.Specialties, "SpecialtyId", "SpecialtyName", trainerSpecialty.SpecialtyId);
            ViewData["TrainerId"] = new SelectList(_context.Trainers, "TrainerId", "TrainerName", trainerSpecialty.TrainerId);
            return View(trainerSpecialty);
        }

        // GET: TrainerSpecialties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TrainerSpecialties == null)
            {
                return NotFound();
            }

            var trainerSpecialty = await _context.TrainerSpecialties
                .Include(t => t.Specialty)
                .Include(t => t.Trainer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (trainerSpecialty == null)
            {
                return NotFound();
            }

            return View(trainerSpecialty);
        }

        // POST: TrainerSpecialties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TrainerSpecialties == null)
            {
                return Problem("Entity set 'WebDevAcademyContext.TrainerSpecialties'  is null.");
            }
            var trainerSpecialty = await _context.TrainerSpecialties.FindAsync(id);
            if (trainerSpecialty != null)
            {
                _context.TrainerSpecialties.Remove(trainerSpecialty);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrainerSpecialtyExists(int id)
        {
          return (_context.TrainerSpecialties?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

COMP003B.AssignmentFinal/Views/Specialties/Create.cshtml
@model COMP003B.AssignmentFinal.Models.Specialty

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Specialty</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SpecialtyName" class="control-label"></label>
                <input asp-for="SpecialtyName" class="form-control" />
                <span asp-validation-for="SpecialtyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpecialtyType" class="control-label"></label>
                <input asp-for="SpecialtyType" class="form-control" />
                <span asp-validation-for="SpecialtyType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

COMP003B.AssignmentFinal/Views/Specialties/Delete.cshtml
@model COMP003B.AssignmentFinal.Models.Specialty

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Specialty</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpecialtyName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpecialtyName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpecialtyType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpecialtyType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SpecialtyId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

COMP003B.AssignmentFinal/Views/Specialties/Details.cshtml
@model COMP003B.AssignmentFinal.Models.Specialty

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Specialty</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpecialtyName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpecialtyName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpecialtyType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpecialtyType)
        </dd>
    </dl>
</div>

<div class="col-md-4">
    <h4>Trainers</h4>
    <ul>
        @foreach (Trainer trainer in ViewBag.Trainers)
        {
                <li>@trainer.TrainerName</li>
        }
    </ul>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.SpecialtyId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

COMP003B.AssignmentFinal/Views/Specialties/Edit.cshtml
@model COMP003B.AssignmentFinal.Models.Specialty

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Specialty</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SpecialtyId" />
            <div class="form-group">
                <label asp-for="SpecialtyName" class="control-label"></label>
                <input asp-for="SpecialtyName" class="form-control" />
                <span asp-validation-for="SpecialtyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpecialtyType" class="control-label"></label>
                <input asp-for="SpecialtyType" class="form-control" />
                <span asp-validation-for="SpecialtyType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

COMP003B.AssignmentFinal/Views/Specialties/Index.cshtml
@model IEnumerable<COMP003B.AssignmentFinal.Models.Specialty>

@{
    ViewData["Title"] = "Index";
}

<h1>Specialties</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.SpecialtyName)</th>
                    <th>@Html.DisplayNameFor(model => model.SpecialtyType)</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="text-center">
                        <td>
                            @Html.DisplayFor(modelItem => item.SpecialtyName)
                        </td>
                        <td >
                            @Html.DisplayFor(modelItem => item.SpecialtyType)
                        </td>
                   
                        <td>
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.SpecialtyId">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                                </svg>
                                Edit
                            </a>
                            <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.SpecialtyId">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-card-text" viewBox="0 0 16 16">
                                    <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z" />
                                    <path d="M3 5.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 8zm0 2.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z" />
                                </svg>

                                Details
                            </a>

                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.SpecialtyId">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                    <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z" />
                                </svg>
                                Delete
                            </a>
                        </td>

                    </tr>
                }
            </tbody>

        </table>

   
<button type="submit" class="btn btn-outline-light">
    <a asp-area="" asp-controller="TrainerSpecialties" asp-action="Index">TrainerSpecialties</a>
</button>
                     