COMP003B.AssignmentFinal/Controllers/GoalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using COMP003B.AssignmentFinal.Data;
using COMP003B.AssignmentFinal.Models;

namespace COMP003B.AssignmentFinal.Controllers
{
    public class GoalsController : Controller
    {
        private readonly WebDevAcademyContext _context;

        public GoalsController(WebDevAcademyContext context)
        {
            _context = context;
        }

        // GET: Goals
        public async Task<IActionResult> Index()
        {
              return _context.Goals != null ? 
                          View(await _context.Goals.ToListAsync()) :
                          Problem("Entity set 'WebDevAcademyContext.Goals'  is null.");
        }

        // GET: Goals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Goals == null)
            {
                return NotFound();
            }

            var goal = await _context.Goals
                .FirstOrDefaultAsync(m => m.GoalId == id);
            if (goal == null)
            {
                return NotFound();
            }

            return View(goal);
        }

        // GET: Goals/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Goals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GoalId,GoalWeight,GoalHealth,GoalBenchPress,GoalSquat,GoalArmCurl,GoalMileTime,GoalStatus")] Goal goal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(goal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(goal);
        }

        // GET: Goals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Goals == null)
            {
                return NotFound();
            }

            var goal = await _context.Goals.FindAsync(id);
            if (goal == null)
            {
                return NotFound();
            }
            return View(goal);
        }

        // POST: Goals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GoalId,GoalWeight,GoalHealth,GoalBenchPress,GoalSquat,GoalArmCurl,GoalMileTime,GoalStatus")] Goal goal)
        {
            if (id != goal.GoalId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(goal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GoalExists(goal.GoalId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(goal);
        }

        // GET: Goals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Goals == null)
            {
                return NotFound();
            }

            var goal = await _context.Goals
                .FirstOrDefaultAsync(m => m.GoalId == id);
            if (goal == null)
            {
                return NotFound();
            }

            return View(goal);
        }

        // POST: Goals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Goals == null)
            {
                return Problem("Entity set 'WebDevAcademyContext.Goals'  is null.");
            }
            var goal = await _context.Goals.FindAsync(id);
            if (goal != null)
            {
                _context.Goals.Remove(goal);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GoalExists(int id)
        {
          return (_context.Goals?.Any(e => e.GoalId == id)).GetValueOrDefault();
        }
    }
}

COMP003B.AssignmentFinal/Controllers/LifetimeDemoController.cs
using COMP003B.AssignmentFinal.Services;
using Microsoft.AspNetCore.Mvc;

namespace COMP003B.AssignmentFinal.Controllers
{
	public class LifetimeDemoController : Controller
	{
		// private fields
		private readonly MyTransientService _transientService1;
		private readonly MyTransientService _transientService2;
		private readonly MyScopedService _scopedService1;
		private readonly MyScopedService _scopedService2;
		private readonly MySingletonService _singletonService1;
		private readonly MySingletonService _singletonService2;
		// constructor
		public LifetimeDemoController(MyTransientService transientService1,
		MyScopedService scopedService1, MySingletonService singletonService1,
		MyTransientService transientService2, MyScopedService scopedService2,
		MySingletonService singletonService2)
		{
			_transientService1 = transientService1;
			_transientService2 = transientService2;
			_scopedService1 = scopedService1;
			_scopedService2 = scopedService2;
			_singletonService1 = singletonService1;
			_singletonService2 = singletonService2;
		}
		public IActionResult Index()
		{
			ViewData["TransientId1"] = _transientService1.GetUniqueId();
			ViewData["TransientId2"] = _transientService2.GetUniqueId();
			ViewData["ScopedId1"] = _scopedService1.GetUniqueId();
			ViewData["ScopedId2"] = _scopedService2.GetUniqueId();
			ViewData["SingletonId1"] = _singletonService1.GetUniqueId();
			ViewData["SingletonId2"] = _singletonService2.GetUniqueId();
			return View();
		}
	}
}

COMP003B.AssignmentFinal/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using COMP003B.AssignmentFinal.Data;
using COMP003B.AssignmentFinal.Models;

namespace COMP003B.AssignmentFinal.Controllers
{
    public class ProfilesController : Controller
    {
        private readonly WebDevAcademyContext _context;

        public ProfilesController(WebDevAcademyContext context)
        {
            _context = context;
        }

        // GET: Profiles
        public async Task<IActionResult> Index()
        {
              return _context.Profiles != null ? 
                          View(await _context.Profiles.ToListAsync()) :
                          Problem("Entity set 'WebDevAcademyContext.Profiles'  is null.");
        }

        // GET: Profiles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Profiles == null)
            {
                return NotFound();
            }

            var profile = await _context.Profiles
                .FirstOrDefaultAsync(m => m.ProfileId == id);
            if (profile == null)
            {
                return NotFound();
            }

            return View(profile);
        }

        // GET: Profiles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Profiles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProfileId,ProfileHeight,ProfileWeight,ProfileGender")] Profile profile)
        {
            if (ModelState.IsValid)
            {
                _context.Add(profile);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(profile);
        }

        // GET: Profiles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Profiles == null)
            {
                return NotFound();
            }

            var profile = await _context.Profiles.FindAsync(id);
            if (profile == null)
            {
                return NotFound();
            }
            return View(profile);
        }

        // POST: Profiles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProfileId,ProfileHeight,ProfileWeight,ProfileGender")] Profile profile)
        {
            if (id != profile.ProfileId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(profile);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfileExists(profile.ProfileId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(profile);
        }

        // GET: Profiles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Profiles == null)
            {
                return NotFound();
            }

            var profile = await _context.Profiles
                .FirstOrDefaultAsync(m => m.ProfileId == id);
            if (profile == null)
            {
                return NotFound();
            }

            return View(profile);
        }

        // POST: Profiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Profiles == null)
            {
                return Problem("Entity set 'WebDevAcademyContext.Profiles'  is null.");
            }
            var profile = await _context.Profiles.FindAsync(id);
            if (profile != null)
            {
                _context.Profiles.Remove(profile);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProfileExists(int id)
        {
          return (_context.Profiles?.Any(e => e.ProfileId == id)).GetValueOrDefault();
        }
    }
}

COMP003B.AssignmentFinal/Controllers/TrainersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using COMP003B.AssignmentFinal.Data;
using COMP003B.AssignmentFinal.Models;

namespace COMP003B.AssignmentFinal.Controllers
{
    public class TrainersController : Controller
    {
        private readonly WebDevAcademyContext _context;

        public TrainersController(WebDevAcademyContext context)
        {
            _context = context;
        }

        // GET: Trainers
        public async Task<IActionResult> Index()
        {
              return _context.Trainers != null ? 
                          View(await _context.Trainers.ToListAsync()) :
                          Problem("Entity set 'WebDevAcademyContext.Trainers'  is null.");
        }

        // GET: Trainers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Trainers == null)
            {
                return NotFound();
            }

            var trainer = await _context.Trainers
                .FirstOrDefaultAsync(m => m.TrainerId == id);
            if (trainer == null)
            {
                return NotFound();
            }

			ViewBag.Specialties = from s in _context.Trainers
							  join e in _context.TrainerSpecialties on s.TrainerId equals e.TrainerId
							  join c in _context.Specialties on e.SpecialtyId equals c.SpecialtyId
							  where s.TrainerId == id
							  select c;

			return View(trainer);
        }

        // GET: Trainers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trainers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TrainerId,TrainerName,TrainerGender,Age")] Trainer trainer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(trainer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(trainer);
        }

        // GET: Trainers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Trainers == null)
            {
                return NotFound();
            }

            var trainer = await _context.Trainers.FindAsync(id);
            if (trainer == null)
            {
                return NotFound();
            }
            return View(trainer);
        }

        // POST: Trainers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TrainerId,TrainerName,TrainerGender,Age")] Trainer trainer)
        {
            if (id != trainer.TrainerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trainer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrainerExists(trainer.TrainerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(trainer);
        }

        // GET: Trainers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Trainers == null)
            {
                return NotFound();
            }

            var trainer = await _context.Trainers
                .FirstOrDefaultAsync(m => m.TrainerId == id);
            if (trainer == null)
            {
                return NotFound();
            }

            return View(trainer);
        }

        // POST: Trainers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Trainers == null)
            {
                return Problem("Entity set 'WebDevAcademyContext.Trainers'  is null.");
            }
            var trainer = await _context.Trainers.FindAsync(id);
            if (trainer != null)
            {
                _context.Trainers.Remove(trainer);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrainerExists(int id)
        {
          return (_context.Trainers?.Any(e => e.TrainerId == id)).GetValueOrDefault();
        }
    }
}

COMP003B.AssignmentFinal/Views/Shared/AboutTheOrganizer.cshtml
<div class="card">
    <div class="card-header text-white bg-success ">
        About the creator
    </div>
    <div class="card-body">
        <blockquote class="blockquote h-100">
            <p>
                Hi everyone! This is Jovani Benavides the creator of the great fitness progam BenaFit. As our program grew we decided it was time to expand and create
                a real facility that our members can come to and work out. This is the first step in a much bigger project and we hope to continue to grow and most importantly
                help you all improve your lifestyle for the better.
            </p>
            <p>Thank you for all the supports!</p>
            <p>
                A little about me, I am young person who decided it was time to help out others who are wanting to improove their health. I have always been into sports
                and fitness and I belive that everyone should be welcome to the fitness comunity. I hope by creating this program and gym it will encourge those who are
                scared to enter a gym or simply just need that push to get going.
            </p>
            <wbr>
        </blockquote>
    </div>
</div>

COMP003B.AssignmentFinal/Views/Shared/_AboutTheOrganizer.cshtml
<div class="card">
    <div class="card-footer text-white bg-success ">
        About
    </div>
    <div class="card-body">
        <blockquote class="blockquote h-100">
            <p>
                Hi everyone! This is Jovani Benavides the creator of the great fitness progam BenaFit. As our program grew we decided it was time to expand and create
                a real facility that our members can come to and work out. This is the first step in a much bigger project and we hope to continue to grow and most importantly
                help you all improve your lifestyle for the better.
            </p>
            <p>Thank you for all the supports!</p>
            <p>
                A little about me, I am young person who decided it was time to help out others who are wanting to improove their health. I have always been into sports
                and fitness and I belive that everyone should be welcome to the fitness comunity. I hope by creating this program and gym it will encourge those who are
                scared to enter a gym or simply just need that push to get going.
            </p>
            <wbr>
        </blockquote>
    </div>
</div>

COMP003B.AssignmentFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - COMP003B.AssignmentFinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/COMP003B.AssignmentFinal.styles.css" asp-append-version="true" />
</head>

<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>


<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">COMP003B.AssignmentFinal</a>              
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trainers" asp-action="Index">Trainers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Specialties" asp-action="Index">Specialties</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TrainerSpecialties" asp-action="Index">TrainerSpecialties</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Goals" asp-action="Index">Goals</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profiles" asp-action="Index">Profiles</a>
                        </li>
         
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LifetimeDemo" asp-action="Index">LifetimeDemo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

 
    <div class="card">
       <div class="card-body">
          <details>
              <summary>Learn about the creator</summary>
              <p>@await Html.PartialAsync("_AboutTheOrganizer")</p>
          </details>
       </div>
    </div>
        
        <footer class="fixed-bottom footer text-muted ">
          <div class="container text-sm-end">
            &copy; 2023 - COMP003B.AssignmentFinal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
          </div>
        </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>